baseURL = "https://ziyang-arch.github.io/"
languageCode = 'en-us'
title = 'A Passanger' # on the life of boat I'm here to leave my trace 
theme = 'PaperMod'

[menu]
    [[menu.main]]
        name = "About me"
        url = "/me/"
        weight = 5
    [[menu.main]]
        name = "Blog"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 20

[params]
    env = 'production'
    description = "PhD Student at UC Riverside | Meta Intern | ex Nvidia Intern"
    author = "Ziyang"

    [params.utterances]
        repo = "ziyang-arch/ziyang-arch.github.io" # Replace with your repo name
        issueTerm = "pathname"
        theme = "github-light"
    
    # Profile Mode (The "Academic" landing page)
    [params.profileMode]
        enabled = true
        title = "A Passanger" 
        motto = "A passenger on this boat of life, here to leave my trace."
        subtitle = "PhD Student in CS @ UC Riverside | GPU Systems for LLM"
        #imageUrl = "/pictures/profile_volcanotop.jpeg" # Place photo in /static folder
        #imageWidth = 180
        #imageHeight = 180

    # Social Icons
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/ziyang-arch"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/ziyang-jia-systemforml"
    [[params.socialIcons]]
        name = "googlescholar"
        url = "https://scholar.google.com/citations?user=hKWh7p4AAAAJ&hl=en"
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true